language: cpp
before_script:
- sudo apt-get install libgtest-dev -y
- sudo apt-get install cmake
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- sudo mkdir /usr/local/lib/gtest
- sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
- sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a 
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- cd $TRAVIS_BUILD_DIR
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uituman4ik:f6fdee75835a66c818dc9ebadcf290afe733ffca "https://api.bintray.com/content/ituman4ik/otus-cpp/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
